spring.application.name=placeboard
server.port=8080

spring.datasource.url=jdbc:postgresql://db.sawhnakwnmkgwqyhsija.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=PlaceBoard@2026

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect