spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=86400000
groq.api.key=${GROQ_API_KEY}
brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=${BREVO_SENDER_EMAIL}
brevo.sender.name=PlaceBoard
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
server.port=${PORT:8080}
server.error.include-message=never
